# Generated by Django 4.2.13 on 2024-05-30 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Relay'), (2, 'Sensor')], default=1, help_text='type')),
                ('name', models.CharField(help_text='Device name', max_length=30)),
                ('pin', models.CharField(choices=[('V0', 'V0'), ('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10'), ('V11', 'V11'), ('V12', 'V12'), ('V13', 'V13'), ('V14', 'V14'), ('V15', 'V15'), ('V16', 'V16'), ('V17', 'V17'), ('V18', 'V18'), ('V19', 'V19'), ('V20', 'V20'), ('V21', 'V21'), ('V22', 'V22'), ('V23', 'V23'), ('V24', 'V24'), ('V25', 'V25'), ('V26', 'V26'), ('V27', 'V27'), ('V28', 'V28'), ('V29', 'V29'), ('V30', 'V30'), ('V31', 'V31'), ('V32', 'V32'), ('V33', 'V33'), ('V34', 'V34'), ('V35', 'V35'), ('V36', 'V36'), ('V37', 'V37'), ('V38', 'V38'), ('V39', 'V39'), ('V40', 'V40'), ('V41', 'V41'), ('V42', 'V42'), ('V43', 'V43'), ('V44', 'V44'), ('V45', 'V45'), ('V46', 'V46'), ('V47', 'V47'), ('V48', 'V48'), ('V49', 'V49'), ('V50', 'V50')], help_text='PIN value from V0 to V50', max_length=3)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=20)),
                ('value', models.CharField(default='0', help_text='Value of the sensor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, help_text='API_KEY', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apikey.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
