# Generated by Django 4.2.13 on 2024-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(default='TEY8OO5iafAV96gRKcZohbO6ED', help_text='Device API Key', max_length=30)),
                ('auto_name', models.CharField(help_text='Tên cây trồng', max_length=100)),
                ('auto_status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=2, help_text='Type')),
                ('pump_choice', models.IntegerField(choices=[(1, 'Cozantinuous Mode (Always On)'), (2, 'Interval Mode (On for 5s, Off for 5s)')], default=1, help_text='Type')),
                ('pump_pin', models.CharField(default='V0', help_text='PIN value from V0 to V50', max_length=3)),
                ('van_status', models.IntegerField(choices=[(1, 'Tu dong'), (2, 'thu cong')], default=1, help_text='Type')),
                ('van_pin', models.CharField(default='V3', help_text='PIN value from V0 to V50', max_length=3)),
                ('min_ph', models.CharField(help_text='ph min', max_length=100)),
                ('max_ph', models.CharField(help_text='ph max', max_length=100)),
                ('ph_status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=1, help_text='Type')),
                ('ph_pin', models.CharField(default='V1', help_text='PIN value from V0 to V50', max_length=3)),
                ('min_light', models.CharField(help_text='light min', max_length=100)),
                ('light_status', models.IntegerField(choices=[(1, 'On'), (2, 'Off')], default=1, help_text='Type')),
                ('light_pin', models.CharField(default='V2', help_text='PIN value from V0 to V50', max_length=3)),
            ],
        ),
    ]
