# Generated by Django 4.2.13 on 2024-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='auto_status',
            field=models.IntegerField(choices=[(1, 'On'), (0, 'Off')], default=0, help_text='Type'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='light_status',
            field=models.IntegerField(choices=[(1, 'On'), (0, 'Off')], default=1, help_text='Type'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='ph_status',
            field=models.IntegerField(choices=[(1, 'On'), (0, 'Off')], default=1, help_text='Type'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='van_status',
            field=models.IntegerField(choices=[(1, 'Tu dong'), (0, 'thu cong')], default=1, help_text='Type'),
        ),
    ]
