# Generated by Django 4.2.13 on 2025-01-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_auto_status_alter_auto_light_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='duong_chat_1',
            field=models.CharField(default='V4', help_text='PIN for dưỡng chất 1 (V0 to V50)', max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='duong_chat_2',
            field=models.CharField(default='V5', help_text='PIN for dưỡng chất 2 (V0 to V50)', max_length=3),
        ),
        migrations.AddField(
            model_name='auto',
            name='duong_chat_3',
            field=models.CharField(default='V6', help_text='PIN for dưỡng chất 3 (V0 to V50)', max_length=3),
        ),
    ]
