# Generated by Django 4.2.13 on 2025-01-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_remove_auto_duong_chat_3_remove_auto_ph_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='light_pin',
            field=models.CharField(default='V11', help_text='PIN value from V0 to V50', max_length=3),
        ),
        migrations.AlterField(
            model_name='auto',
            name='van_pin',
            field=models.CharField(default='Vx', help_text='PIN value from V0 to V50', max_length=3),
        ),
    ]
