# Generated by Django 4.2.13 on 2025-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_auto_vanph_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='light_relay',
            field=models.CharField(default='V11', help_text='PIN value from V0 to V50', max_length=3),
        ),
        migrations.AlterField(
            model_name='auto',
            name='light_pin',
            field=models.CharField(default='V6', help_text='PIN value from V0 to V50', max_length=3),
        ),
    ]
